-- Initial migration placeholder for Prisma.
--
-- Notes:
-- 1) This migration should ideally be generated by running
--    npm run db:migrate -- --name init
-- 2) After generation, replace this placeholder with actual SQL.

/*
  SELECT 1;
*/
